export const tags = [
  { value: 'Incubation' },
  { value: 'Acceleration Programs' },
  { value: 'Startup Guidance' },
  { value: 'Mentorship' },
  { value: 'Entrepreneurship' },
  { value: 'Innovation' },
  { value: 'Networking' },
  { value: 'Startup Funding' },
  { value: 'Product Design' },
  { value: 'Growth Hacking' },
  { value: 'Market Research' },
  { value: 'Business Development' },
  { value: 'Digital Transformation' },
  { value: 'Customer Acquisition' },
  { value: 'Venture Capital' },
  { value: 'User Experience' },
  { value: 'Data Analytics' },
  { value: 'Sustainable Business' },
  { value: 'Leadership Training' },
  { value: 'Social Media Handling' },
  { value: 'Content Creation' },
  { value: 'SEO (Search Engine Optimization)' },
  { value: 'SEM (Search Engine Marketing)' },
  { value: 'Influencer Marketing' },
  { value: 'Paid Advertising (PPC, Social Media Ads)' },
  { value: 'Email Marketing' },
  { value: 'Community Building' },
  { value: 'Growth Marketing Strategies' },
  { value: 'Digital Marketing' },
  { value: 'Tele Marketing' },
  { value: 'Financial Planning & Budgeting' },
  { value: 'Bookkeeping' },
  { value: 'Invoicing & Payment Solutions' },
  { value: 'Payroll Management' },
  { value: 'Financial Auditing' },
  { value: 'Tax Preparation & Filing' },
  { value: 'Business Valuation' },
  { value: 'Cash Flow Management' },
  { value: 'Pitch Deck Expert' },
  { value: 'Pitch Deck Creation' },
  { value: 'Fundraising Strategy' },
  { value: 'Investor Relations' },
  { value: 'Venture Capital Advisory' },
  { value: 'Crowdfunding Support' },
  { value: 'Sales Strategy' },
  { value: 'CRM (Customer Relationship Management)' },
  { value: 'Sales Funnel Optimization' },
  { value: 'Cold Calling & Outreach' },
  { value: 'Partnership Building' },
  { value: 'Client Acquisition' },
  { value: 'Business Networking' },
  { value: 'Affiliate Marketing Programs' },
  { value: 'Recruitment Services' },
  { value: 'Talent Sourcing' },
  { value: 'Employee Onboarding' },
  { value: 'HR Management Software' },
  { value: 'Team Building & Training' },
  { value: 'Performance Management' },
  { value: 'Diversity and Inclusion Programs' },
  { value: 'Compensation Planning' },
  { value: 'Freelance Hiring Platforms' },
  { value: 'Remote Work Solutions' },
  { value: 'HR Compliance' },
  { value: 'Supply Chain Management' },
  { value: 'Logistics & Fulfillment' },
  { value: 'Inventory Management' },
  { value: 'Shipping & Delivery Services' },
  { value: 'Procurement Services' },
  { value: 'Vendor Management' },
  { value: 'Workspace Optimization' },
  { value: 'Manufacturing Services' },
  { value: 'Packaging Design & Production' },
  { value: 'Customer Service Tools (Helpdesk, CRM)' },
  { value: 'Chatbot Integration' },
  { value: 'Support Training Programs' },
  { value: 'Call Center Services' },
  { value: 'Client Feedback & Surveys' },
  { value: 'Community Management' },
  { value: 'Ticketing Systems' },
  { value: 'Customer Retention Strategies' },
  { value: 'Go-to-Market Strategy' },
  { value: 'Launch Event Planning' },
  { value: 'Product Demo Creation' },
  { value: 'Press Release Writing' },
  { value: 'Beta Testing Coordination' },
  { value: 'Early Adopter Outreach' },
  { value: 'Media Outreach and PR' },
  { value: 'Trade Show Support' },
  { value: 'Influencer Partnerships for Launch' },
  { value: 'Post-launch Support' },
  { value: 'Market Analysis & Research' },
  { value: 'Competitor Analysis' },
  { value: 'Customer Segmentation' },
  { value: 'Data Collection & Management' },
  { value: 'Predictive Analytics' },
  { value: 'A/B Testing' },
  { value: 'Data Visualization & Reporting' },
  { value: 'Business Intelligence Tools' },
  { value: 'User Analytics (Web, App)' },
  { value: 'KPI Tracking & Dashboards' },
  { value: 'Customer Journey Mapping' },
  { value: 'Feedback Loops & Surveys' },
  { value: 'Net Promoter Score (NPS) Programs' },
  { value: 'User Onboarding Tools' },
  { value: 'Loyalty Programs' },
  { value: 'Personalization & Targeting Strategies' },
  { value: 'Customer Success Management' },
  { value: 'Research & Development (R&D)' },
  { value: 'Patent Filing & Protection' },
  { value: 'Product Innovation Workshops' },
  { value: 'Feasibility Studies' },
  { value: 'Innovation Funding Programs' },
  { value: 'Sustainable Sourcing' },
  { value: 'Corporate Social Responsibility (CSR) Programs' },
  { value: 'Green Product Design' },
  { value: 'Carbon Footprint Reduction Initiatives' },
  { value: 'Energy Efficiency Solutions' },
  { value: 'Ethics & Compliance Programs' },
  { value: 'Vision & Mission Development' },
  { value: 'Cross-functional Collaboration' },
];

export const categories = [
  { value: 'Incubation' },
  { value: 'Acceleration Programs' },
  { value: 'Startup Guidance' },
  { value: 'MVP Creation' },
  { value: 'Website Creation' },
  { value: 'Marketing Support' },
  { value: 'Branding' },
  { value: 'Social Media Handling' },
  { value: 'Pitch Deck Expert' },
  { value: 'Pitch Deck Creation' },
  { value: 'Prototype Making (Digital)' },
  { value: 'Prototype Making (Hardware)' },
  { value: 'Coworking Space' },
  { value: 'Finance' },
  { value: 'Sales' },
  { value: 'Others' },
];

export const locations = [
  { value: 'Andaman and Nicobar Islands' },
  { value: 'Andhra Pradesh' },
  { value: 'Arunachal Pradesh' },
  { value: 'Assam' },
  { value: 'Bihar' },
  { value: 'Chandigarh' },
  { value: 'Chhattisgarh' },
  { value: 'Dadra and Nagar Haveli and Daman and Diu' },
  { value: 'Delhi' },
  { value: 'Goa' },
  { value: 'Gujarat' },
  { value: 'Haryana' },
  { value: 'Himachal Pradesh' },
  { value: 'Jharkhand' },
  { value: 'Karnataka' },
  { value: 'Kerala' },
  { value: 'Madhya Pradesh' },
  { value: 'Maharashtra' },
  { value: 'Manipur' },
  { value: 'Meghalaya' },
  { value: 'Mizoram' },
  { value: 'Nagaland' },
  { value: 'Odisha' },
  { value: 'Punjab' },
  { value: 'Rajasthan' },
  { value: 'Sikkim' },
  { value: 'Tamil Nadu' },
  { value: 'Telangana' },
  { value: 'Tripura' },
  { value: 'Uttar Pradesh' },
  { value: 'Uttarakhand' },
  { value: 'West Bengal' },
  { value: 'Others' },
];

export const countryCodes = [
  { value: 'United States (+1)' },
  { value: 'Russia (+7)' },
  { value: 'Egypt (+20)' },
  { value: 'South Africa (+27)' },
  { value: 'Greece (+30)' },
  { value: 'Netherlands (+31)' },
  { value: 'Belgium (+32)' },
  { value: 'France (+33)' },
  { value: 'Spain (+34)' },
  { value: 'Hungary (+36)' },
  { value: 'Italy (+39)' },
  { value: 'Switzerland (+41)' },
  { value: 'Austria (+43)' },
  { value: 'United Kingdom (+44)' },
  { value: 'Denmark (+45)' },
  { value: 'Sweden (+46)' },
  { value: 'Norway (+47)' },
  { value: 'Poland (+48)' },
  { value: 'Germany (+49)' },
  { value: 'Peru (+51)' },
  { value: 'Mexico (+52)' },
  { value: 'Cuba (+53)' },
  { value: 'Argentina (+54)' },
  { value: 'Brazil (+55)' },
  { value: 'Chile (+56)' },
  { value: 'Colombia (+57)' },
  { value: 'Venezuela (+58)' },
  { value: 'Malaysia (+60)' },
  { value: 'Australia (+61)' },
  { value: 'Indonesia (+62)' },
  { value: 'Philippines (+63)' },
  { value: 'New Zealand (+64)' },
  { value: 'Singapore (+65)' },
  { value: 'Thailand (+66)' },
  { value: 'Japan (+81)' },
  { value: 'South Korea (+82)' },
  { value: 'Vietnam (+84)' },
  { value: 'China (+86)' },
  { value: 'Turkey (+90)' },
  { value: 'India (+91)' },
  { value: 'Pakistan (+92)' },
  { value: 'Afghanistan (+93)' },
  { value: 'Sri Lanka (+94)' },
  { value: 'Myanmar (+95)' },
  { value: 'Maldives (+960)' },
  { value: 'Lebanon (+961)' },
  { value: 'Jordan (+962)' },
  { value: 'Syria (+963)' },
  { value: 'Iraq (+964)' },
  { value: 'Kuwait (+965)' },
  { value: 'Saudi Arabia (+966)' },
  { value: 'Yemen (+967)' },
  { value: 'Oman (+968)' },
  { value: 'Palestine (+970)' },
  { value: 'United Arab Emirates (+971)' },
  { value: 'Israel (+972)' },
  { value: 'Bahrain (+973)' },
  { value: 'Qatar (+974)' },
  { value: 'Bhutan (+975)' },
  { value: 'Mongolia (+976)' },
  { value: 'Nepal (+977)' },
  { value: 'Tajikistan (+992)' },
  { value: 'Turkmenistan (+993)' },
  { value: 'Azerbaijan (+994)' },
  { value: 'Georgia (+995)' },
  { value: 'Kyrgyzstan (+996)' },
  { value: 'Uzbekistan (+998)' },
  { value: 'Ethiopia (+251)' },
  { value: 'Somalia (+252)' },
  { value: 'Djibouti (+253)' },
  { value: 'Kenya (+254)' },
  { value: 'Tanzania (+255)' },
  { value: 'Uganda (+256)' },
  { value: 'Burundi (+257)' },
  { value: 'Mozambique (+258)' },
  { value: 'Zambia (+260)' },
  { value: 'Madagascar (+261)' },
  { value: 'Réunion (+262)' },
  { value: 'Zimbabwe (+263)' },
  { value: 'Namibia (+264)' },
  { value: 'Malawi (+265)' },
  { value: 'Lesotho (+266)' },
  { value: 'Botswana (+267)' },
  { value: 'Eswatini (+268)' },
  { value: 'Comoros (+269)' },
  { value: 'Saint Helena (+290)' },
  { value: 'Eritrea (+291)' },
  { value: 'Aruba (+297)' },
  { value: 'Faroe Islands (+298)' },
  { value: 'Greenland (+299)' },
];

export const industries = [
  { value: 'Advertising' },
  { value: 'Agriculture' },
  { value: 'AI (Artificial Intelligence)' },
  { value: 'Analytics' },
  { value: 'AR/VR (Augmented Reality/Virtual Reality)' },
  { value: 'Automotive' },
  { value: 'Banking' },
  { value: 'Construction' },
  { value: 'Consumer Goods' },
  { value: 'Dating/Social Networking' },
  { value: 'Design' },
  { value: 'Education' },
  { value: 'Energy & Utilities' },
  { value: 'Enterprise Software' },
  { value: 'Events' },
  { value: 'Fashion' },
  { value: 'Finance Technology' },
  { value: 'Food & Beverages' },
  { value: 'Gaming' },
  { value: 'Healthcare & Lifesciences' },
  { value: 'Human Resources' },
  { value: 'IT Services' },
  { value: 'Logistics' },
  { value: 'Manufacturing' },
  { value: 'Media & Entertainment' },
  { value: 'Nanotechnology' },
  { value: 'Retail' },
  { value: 'Robotics' },
  { value: 'Security' },
  { value: 'Sports' },
  { value: 'Telecommunications' },
  { value: 'Textiles & Apparel' },
  { value: 'Transportation' },
  { value: 'Travel & Tourism' },
  { value: 'Waste Management' },
  { value: 'Water Management' },
  { value: 'Others' },
];

export const sectors = [
  { value: 'Digital Advertising' },
  { value: 'Print Advertising' },
  { value: 'Media Buying' },
  { value: 'Agri-Tech' },
  { value: 'Farming' },
  { value: 'Organic Farming' },
  { value: 'Machine Learning' },
  { value: 'Robotics' },
  { value: 'Natural Language Processing' },
  { value: 'Data Analytics' },
  { value: 'Big Data' },
  { value: 'Predictive Analytics' },
  { value: 'Virtual Reality Hardware' },
  { value: 'Augmented Reality Software' },
  { value: 'Mixed Reality' },
  { value: 'Electric Vehicles' },
  { value: 'Vehicle Maintenance' },
  { value: 'Car Rentals' },
  { value: 'Digital Banking' },
  { value: 'FinTech' },
  { value: 'Neobanking' },
  { value: 'Construction Tech' },
  { value: 'Smart Buildings' },
  { value: 'Real Estate Development' },
  { value: 'Fast Moving Consumer Goods (FMCG)' },
  { value: 'Consumer Electronics' },
  { value: 'Household Products' },
  { value: 'Online Dating Platforms' },
  { value: 'Social Media Applications' },
  { value: 'Community Building Platforms' },
  { value: 'Graphic Design' },
  { value: 'Industrial Design' },
  { value: 'UX/UI Design' },
  { value: 'EdTech' },
  { value: 'Online Tutoring' },
  { value: 'Educational Content' },
  { value: 'Renewable Energy' },
  { value: 'Smart Grids' },
  { value: 'Energy Storage' },
  { value: 'Business Management Software' },
  { value: 'Customer Relationship Management (CRM)' },
  { value: 'Enterprise Resource Planning (ERP)' },
  { value: 'Event Management' },
  { value: 'Virtual Events' },
  { value: 'Ticketing Solutions' },
  { value: 'Fashion Tech' },
  { value: 'Online Fashion Retail' },
  { value: 'Sustainable Fashion' },
  { value: 'Payment Solutions' },
  { value: 'Personal Finance Management' },
  { value: 'Cryptocurrency' },
  { value: 'Food Delivery' },
  { value: 'Restaurant Tech' },
  { value: 'Packaged Foods' },
  { value: 'Mobile Games' },
  { value: 'eSports' },
  { value: 'Game Development' },
  { value: 'HealthTech' },
  { value: 'Biotechnology' },
  { value: 'Medical Devices' },
  { value: 'HR Tech' },
  { value: 'Recruitment Platforms' },
  { value: 'Employee Engagement' },
  { value: 'Cloud Computing' },
  { value: 'IT Consulting' },
  { value: 'Supply Chain Management' },
  { value: 'Freight Services' },
  { value: 'Last-Mile Delivery' },
  { value: 'Smart Manufacturing' },
  { value: 'Industrial IoT' },
  { value: '3D Printing' },
  { value: 'Digital Media' },
  { value: 'Content Creation' },
  { value: 'OTT Platforms' },
  { value: 'Nano-Materials' },
  { value: 'Nano-Medicine' },
  { value: 'Nano-Devices' },
  { value: 'E-Commerce' },
  { value: 'Brick-and-Mortar Retail' },
  { value: 'Retail Tech' },
  { value: 'Industrial Robots' },
  { value: 'Service Robots' },
  { value: 'Robotic Process Automation (RPA)' },
  { value: 'Physical Security' },
  { value: 'Cybersecurity' },
  { value: 'Surveillance Systems' },
  { value: 'Sports Tech' },
  { value: 'Fitness Tech' },
  { value: 'Sports Analytics' },
  { value: 'Telecom Services' },
  { value: 'Network Equipment' },
  { value: 'IoT Connectivity' },
  { value: 'Textile Manufacturing' },
  { value: 'Apparel Design' },
  { value: 'Smart Textiles' },
  { value: 'Ride-Sharing' },
  { value: 'Fleet Management' },
  { value: 'Public Transport Solutions' },
  { value: 'Travel Tech' },
  { value: 'Tourism Services' },
  { value: 'Hospitality Tech' },
  { value: 'Recycling Solutions' },
  { value: 'Waste-to-Energy' },
  { value: 'E-Waste Management' },
  { value: 'Water Purification' },
  { value: 'Smart Water Systems' },
  { value: 'Water Conservation Technologies' },
  { value: 'Others' },
];

export const trlLevels = [
  { value: 'TRL 1: Basic Research' },
  { value: 'TRL 2: Applied Research' },
  { value: 'TRL 3: Critical Function or Proof of Concept Established' },
  {
    value: 'TRL 4: Lab Testing/Validation of Alpha Prototype Component/Process',
  },
  { value: 'TRL 5: Laboratory Testing of Integrated/Semi-Integrated System' },
  { value: 'TRL 6: Prototype System Verified' },
  { value: 'TRL 7: Integrated Pilot System Demonstrated' },
  { value: 'TRL 8: System Incorporated in Commercial Design' },
  { value: 'TRL 9: System Proven and Ready for Full Commercial Deployment' },
];
