export const tags = [
  { value: 'incubation', label: 'Incubation' },
  { value: 'acceleration-programs', label: 'Acceleration Programs' },
  { value: 'startup-guidance', label: 'Startup Guidance' },
  { value: 'mentorship', label: 'Mentorship' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'innovation', label: 'Innovation' },
  { value: 'networking', label: 'Networking' },
  { value: 'startup-funding', label: 'Startup Funding' },
  { value: 'product-design', label: 'Product Design' },
  { value: 'growth-hacking', label: 'Growth Hacking' },
  { value: 'market-research', label: 'Market Research' },
  { value: 'business-development', label: 'Business Development' },
  { value: 'digital-transformation', label: 'Digital Transformation' },
  { value: 'customer-acquisition', label: 'Customer Acquisition' },
  { value: 'venture-capital', label: 'Venture Capital' },
  { value: 'user-experience', label: 'User Experience (UX)' },
  { value: 'data-analytics', label: 'Data Analytics' },
  { value: 'sustainable-business', label: 'Sustainable Business' },
  { value: 'leadership-training', label: 'Leadership Training' },
  { value: 'social-media-handling', label: 'Social Media Handling' },
  { value: 'content-creation', label: 'Content Creation' },
  { value: 'seo', label: 'SEO (Search Engine Optimization)' },
  { value: 'sem', label: 'SEM (Search Engine Marketing)' },
  { value: 'influencer-marketing', label: 'Influencer Marketing' },
  {
    value: 'paid-advertising',
    label: 'Paid Advertising (PPC, Social Media Ads)',
  },
  { value: 'email-marketing', label: 'Email Marketing' },
  { value: 'community-building', label: 'Community Building' },
  {
    value: 'growth-marketing-strategies',
    label: 'Growth Marketing Strategies',
  },
  { value: 'digital-marketing', label: 'Digital Marketing' },
  { value: 'tele-marketing', label: 'Tele Marketing' },
  { value: 'financial-planning', label: 'Financial Planning & Budgeting' },
  { value: 'bookkeeping', label: 'Bookkeeping' },
  { value: 'invoicing', label: 'Invoicing & Payment Solutions' },
  { value: 'payroll-management', label: 'Payroll Management' },
  { value: 'financial-auditing', label: 'Financial Auditing' },
  { value: 'tax-preparation', label: 'Tax Preparation & Filing' },
  { value: 'business-valuation', label: 'Business Valuation' },
  { value: 'cash-flow-management', label: 'Cash Flow Management' },
  { value: 'pitch-deck-expert', label: 'Pitch Deck Expert' },
  { value: 'pitch-deck-creation', label: 'Pitch Deck Creation' },
  { value: 'fundraising-strategy', label: 'Fundraising Strategy' },
  { value: 'investor-relations', label: 'Investor Relations' },
  { value: 'venture-capital-advisory', label: 'Venture Capital Advisory' },
  { value: 'crowdfunding-support', label: 'Crowdfunding Support' },
  { value: 'sales-strategy', label: 'Sales Strategy' },
  { value: 'crm', label: 'CRM (Customer Relationship Management)' },
  { value: 'sales-funnel-optimization', label: 'Sales Funnel Optimization' },
  { value: 'cold-calling', label: 'Cold Calling & Outreach' },
  { value: 'partnership-building', label: 'Partnership Building' },
  { value: 'client-acquisition', label: 'Client Acquisition' },
  { value: 'business-networking', label: 'Business Networking' },
  {
    value: 'affiliate-marketing-programs',
    label: 'Affiliate Marketing Programs',
  },
  { value: 'recruitment-services', label: 'Recruitment Services' },
  { value: 'talent-sourcing', label: 'Talent Sourcing' },
  { value: 'employee-onboarding', label: 'Employee Onboarding' },
  { value: 'hr-management-software', label: 'HR Management Software' },
  { value: 'team-building', label: 'Team Building & Training' },
  { value: 'performance-management', label: 'Performance Management' },
  { value: 'diversity-inclusion', label: 'Diversity and Inclusion Programs' },
  { value: 'compensation-planning', label: 'Compensation Planning' },
  { value: 'freelance-hiring', label: 'Freelance Hiring Platforms' },
  { value: 'remote-work-solutions', label: 'Remote Work Solutions' },
  { value: 'hr-compliance', label: 'HR Compliance' },
  { value: 'supply-chain-management', label: 'Supply Chain Management' },
  { value: 'logistics-fulfillment', label: 'Logistics & Fulfillment' },
  { value: 'inventory-management', label: 'Inventory Management' },
  { value: 'shipping-delivery', label: 'Shipping & Delivery Services' },
  { value: 'procurement-services', label: 'Procurement Services' },
  { value: 'vendor-management', label: 'Vendor Management' },
  { value: 'workspace-optimization', label: 'Workspace Optimization' },
  { value: 'manufacturing-services', label: 'Manufacturing Services' },
  { value: 'packaging-design', label: 'Packaging Design & Production' },
  {
    value: 'customer-service-tools',
    label: 'Customer Service Tools (Helpdesk, CRM)',
  },
  { value: 'chatbot-integration', label: 'Chatbot Integration' },
  { value: 'support-training-programs', label: 'Support Training Programs' },
  { value: 'call-center-services', label: 'Call Center Services' },
  { value: 'client-feedback', label: 'Client Feedback & Surveys' },
  { value: 'community-management', label: 'Community Management' },
  { value: 'ticketing-systems', label: 'Ticketing Systems' },
  {
    value: 'customer-retention-strategies',
    label: 'Customer Retention Strategies',
  },
  { value: 'go-to-market-strategy', label: 'Go-to-Market Strategy' },
  { value: 'launch-event-planning', label: 'Launch Event Planning' },
  { value: 'product-demo-creation', label: 'Product Demo Creation' },
  { value: 'press-release-writing', label: 'Press Release Writing' },
  { value: 'beta-testing-coordination', label: 'Beta Testing Coordination' },
  { value: 'early-adopter-outreach', label: 'Early Adopter Outreach' },
  { value: 'media-outreach-pr', label: 'Media Outreach and PR' },
  { value: 'trade-show-support', label: 'Trade Show Support' },
  {
    value: 'influencer-partnerships',
    label: 'Influencer Partnerships for Launch',
  },
  { value: 'post-launch-support', label: 'Post-launch Support' },
  { value: 'market-analysis', label: 'Market Analysis & Research' },
  { value: 'competitor-analysis', label: 'Competitor Analysis' },
  { value: 'customer-segmentation', label: 'Customer Segmentation' },
  { value: 'data-collection', label: 'Data Collection & Management' },
  { value: 'predictive-analytics', label: 'Predictive Analytics' },
  { value: 'a-b-testing', label: 'A/B Testing' },
  { value: 'data-visualization', label: 'Data Visualization & Reporting' },
  {
    value: 'business-intelligence-tools',
    label: 'Business Intelligence Tools',
  },
  { value: 'user-analytics', label: 'User Analytics (Web, App)' },
  { value: 'kpi-tracking', label: 'KPI Tracking & Dashboards' },
  { value: 'customer-journey-mapping', label: 'Customer Journey Mapping' },
  { value: 'feedback-loops-surveys', label: 'Feedback Loops & Surveys' },
  { value: 'nps-programs', label: 'Net Promoter Score (NPS) Programs' },
  { value: 'user-onboarding-tools', label: 'User Onboarding Tools' },
  { value: 'loyalty-programs', label: 'Loyalty Programs' },
  {
    value: 'personalization-strategies',
    label: 'Personalization & Targeting Strategies',
  },
  {
    value: 'customer-success-management',
    label: 'Customer Success Management',
  },
  { value: 'r-d', label: 'Research & Development (R&D)' },
  { value: 'patent-filing', label: 'Patent Filing & Protection' },
  {
    value: 'product-innovation-workshops',
    label: 'Product Innovation Workshops',
  },
  { value: 'feasibility-studies', label: 'Feasibility Studies' },
  {
    value: 'innovation-funding-programs',
    label: 'Innovation Funding Programs',
  },
  { value: 'sustainable-sourcing', label: 'Sustainable Sourcing' },
  { value: 'csr', label: 'Corporate Social Responsibility (CSR) Programs' },
  { value: 'green-product-design', label: 'Green Product Design' },
  {
    value: 'carbon-footprint-reduction',
    label: 'Carbon Footprint Reduction Initiatives',
  },
  { value: 'energy-efficiency', label: 'Energy Efficiency Solutions' },
  { value: 'ethics-compliance', label: 'Ethics & Compliance Programs' },
  {
    value: 'vision-mission-development',
    label: 'Vision & Mission Development',
  },
  {
    value: 'cross-functional-collaboration',
    label: 'Cross-functional Collaboration',
  },
];

export const categories = [
  { value: 'incubation', label: 'Incubation' },
  { value: 'acceleration-programs', label: 'Acceleration Programs' },
  { value: 'startup-guidance', label: 'Startup Guidance' },
  { value: 'mvp-creation', label: 'MVP Creation' },
  { value: 'website-creation', label: 'Website Creation' },
  { value: 'marketing-support', label: 'Marketing Support' },
  { value: 'branding', label: 'Branding' },
  { value: 'social-media-handling', label: 'Social Media Handling' },
  { value: 'pitch-deck-expert', label: 'Pitch Deck Expert' },
  { value: 'pitch-deck-creation', label: 'Pitch Deck Creation' },
  { value: 'prototype-making-digital', label: 'Prototype Making (Digital)' },
  { value: 'prototype-making-hardware', label: 'Prototype Making (Hardware)' },
  { value: 'coworking-space', label: 'Coworking Space' },
  { value: 'finance', label: 'Finance' },
  { value: 'sales', label: 'Sales' },
  { value: 'others', label: 'Others' },
];

export const locations = [
  { value: 'andaman-nicobar', label: 'Andaman and Nicobar Islands' },
  { value: 'andhra-pradesh', label: 'Andhra Pradesh' },
  { value: 'arunachal-pradesh', label: 'Arunachal Pradesh' },
  { value: 'assam', label: 'Assam' },
  { value: 'bihar', label: 'Bihar' },
  { value: 'chandigarh', label: 'Chandigarh' },
  { value: 'chhattisgarh', label: 'Chhattisgarh' },
  {
    value: 'dadra-nagar-haveli-daman-diu',
    label: 'Dadra and Nagar Haveli and Daman and Diu',
  },
  { value: 'delhi', label: 'Delhi' },
  { value: 'goa', label: 'Goa' },
  { value: 'gujarat', label: 'Gujarat' },
  { value: 'haryana', label: 'Haryana' },
  { value: 'himachal-pradesh', label: 'Himachal Pradesh' },
  { value: 'jharkhand', label: 'Jharkhand' },
  { value: 'karnataka', label: 'Karnataka' },
  { value: 'kerala', label: 'Kerala' },
  { value: 'madhya-pradesh', label: 'Madhya Pradesh' },
  { value: 'maharashtra', label: 'Maharashtra' },
  { value: 'manipur', label: 'Manipur' },
  { value: 'meghalaya', label: 'Meghalaya' },
  { value: 'mizoram', label: 'Mizoram' },
  { value: 'nagaland', label: 'Nagaland' },
  { value: 'odisha', label: 'Odisha' },
  { value: 'punjab', label: 'Punjab' },
  { value: 'rajasthan', label: 'Rajasthan' },
  { value: 'sikkim', label: 'Sikkim' },
  { value: 'tamil-nadu', label: 'Tamil Nadu' },
  { value: 'telangana', label: 'Telangana' },
  { value: 'tripura', label: 'Tripura' },
  { value: 'uttar-pradesh', label: 'Uttar Pradesh' },
  { value: 'uttarakhand', label: 'Uttarakhand' },
  { value: 'west-bengal', label: 'West Bengal' },
  { value: 'other', label: 'Other' },
];

export const countryCodes = [
  { value: '+1', label: '+1' },
  { value: '+7', label: '+7' },
  { value: '+20', label: '+20' },
  { value: '+27', label: '+27' },
  { value: '+30', label: '+30' },
  { value: '+31', label: '+31' },
  { value: '+32', label: '+32' },
  { value: '+33', label: '+33' },
  { value: '+34', label: '+34' },
  { value: '+36', label: '+36' },
  { value: '+39', label: '+39' },
  { value: '+41', label: '+41' },
  { value: '+43', label: '+43' },
  { value: '+44', label: '+44' },
  { value: '+45', label: '+45' },
  { value: '+46', label: '+46' },
  { value: '+47', label: '+47' },
  { value: '+48', label: '+48' },
  { value: '+49', label: '+49' },
  { value: '+51', label: '+51' },
  { value: '+52', label: '+52' },
  { value: '+53', label: '+53' },
  { value: '+54', label: '+54' },
  { value: '+55', label: '+55' },
  { value: '+56', label: '+56' },
  { value: '+57', label: '+57' },
  { value: '+58', label: '+58' },
  { value: '+60', label: '+60' },
  { value: '+61', label: '+61' },
  { value: '+62', label: '+62' },
  { value: '+63', label: '+63' },
  { value: '+64', label: '+64' },
  { value: '+65', label: '+65' },
  { value: '+66', label: '+66' },
  { value: '+81', label: '+81' },
  { value: '+82', label: '+82' },
  { value: '+84', label: '+84' },
  { value: '+86', label: '+86' },
  { value: '+90', label: '+90' },
  { value: '+91', label: '+91' },
  { value: '+92', label: '+92' },
  { value: '+93', label: '+93' },
  { value: '+94', label: '+94' },
  { value: '+95', label: '+95' },
  { value: '+96', label: '+96' },
  { value: '+960', label: '+960' },
  { value: '+961', label: '+961' },
  { value: '+962', label: '+962' },
  { value: '+963', label: '+963' },
  { value: '+964', label: '+964' },
  { value: '+965', label: '+965' },
  { value: '+966', label: '+966' },
  { value: '+967', label: '+967' },
  { value: '+968', label: '+968' },
  { value: '+970', label: '+970' },
  { value: '+971', label: '+971' },
  { value: '+972', label: '+972' },
  { value: '+973', label: '+973' },
  { value: '+974', label: '+974' },
  { value: '+975', label: '+975' },
  { value: '+976', label: '+976' },
  { value: '+977', label: '+977' },
  { value: '+992', label: '+992' },
  { value: '+993', label: '+993' },
  { value: '+994', label: '+994' },
  { value: '+995', label: '+995' },
  { value: '+996', label: '+996' },
  { value: '+998', label: '+998' },
  { value: '+251', label: '+251' },
  { value: '+252', label: '+252' },
  { value: '+253', label: '+253' },
  { value: '+254', label: '+254' },
  { value: '+255', label: '+255' },
  { value: '+256', label: '+256' },
  { value: '+257', label: '+257' },
  { value: '+258', label: '+258' },
  { value: '+260', label: '+260' },
  { value: '+261', label: '+261' },
  { value: '+262', label: '+262' },
  { value: '+263', label: '+263' },
  { value: '+264', label: '+264' },
  { value: '+265', label: '+265' },
  { value: '+266', label: '+266' },
  { value: '+267', label: '+267' },
  { value: '+268', label: '+268' },
  { value: '+269', label: '+269' },
  { value: '+290', label: '+290' },
  { value: '+291', label: '+291' },
  { value: '+297', label: '+297' },
  { value: '+298', label: '+298' },
  { value: '+299', label: '+299' },
];
