export const tags = [
  { value: 'Incubation' },
  { value: 'Acceleration Programs' },
  { value: 'Startup Guidance' },
  { value: 'Mentorship' },
  { value: 'Entrepreneurship' },
  { value: 'Innovation' },
  { value: 'Networking' },
  { value: 'Startup Funding' },
  { value: 'Product Design' },
  { value: 'Growth Hacking' },
  { value: 'Market Research' },
  { value: 'Business Development' },
  { value: 'Digital Transformation' },
  { value: 'Customer Acquisition' },
  { value: 'Venture Capital' },
  { value: 'User Experience' },
  { value: 'Data Analytics' },
  { value: 'Sustainable Business' },
  { value: 'Leadership Training' },
  { value: 'Social Media Handling' },
  { value: 'Content Creation' },
  { value: 'SEO (Search Engine Optimization)' },
  { value: 'SEM (Search Engine Marketing)' },
  { value: 'Influencer Marketing' },
  { value: 'Paid Advertising (PPC, Social Media Ads)' },
  { value: 'Email Marketing' },
  { value: 'Community Building' },
  { value: 'Growth Marketing Strategies' },
  { value: 'Digital Marketing' },
  { value: 'Tele Marketing' },
  { value: 'Financial Planning & Budgeting' },
  { value: 'Bookkeeping' },
  { value: 'Invoicing & Payment Solutions' },
  { value: 'Payroll Management' },
  { value: 'Financial Auditing' },
  { value: 'Tax Preparation & Filing' },
  { value: 'Business Valuation' },
  { value: 'Cash Flow Management' },
  { value: 'Pitch Deck Expert' },
  { value: 'Pitch Deck Creation' },
  { value: 'Fundraising Strategy' },
  { value: 'Investor Relations' },
  { value: 'Venture Capital Advisory' },
  { value: 'Crowdfunding Support' },
  { value: 'Sales Strategy' },
  { value: 'CRM (Customer Relationship Management)' },
  { value: 'Sales Funnel Optimization' },
  { value: 'Cold Calling & Outreach' },
  { value: 'Partnership Building' },
  { value: 'Client Acquisition' },
  { value: 'Business Networking' },
  { value: 'Affiliate Marketing Programs' },
  { value: 'Recruitment Services' },
  { value: 'Talent Sourcing' },
  { value: 'Employee Onboarding' },
  { value: 'HR Management Software' },
  { value: 'Team Building & Training' },
  { value: 'Performance Management' },
  { value: 'Diversity and Inclusion Programs' },
  { value: 'Compensation Planning' },
  { value: 'Freelance Hiring Platforms' },
  { value: 'Remote Work Solutions' },
  { value: 'HR Compliance' },
  { value: 'Supply Chain Management' },
  { value: 'Logistics & Fulfillment' },
  { value: 'Inventory Management' },
  { value: 'Shipping & Delivery Services' },
  { value: 'Procurement Services' },
  { value: 'Vendor Management' },
  { value: 'Workspace Optimization' },
  { value: 'Manufacturing Services' },
  { value: 'Packaging Design & Production' },
  { value: 'Customer Service Tools (Helpdesk, CRM)' },
  { value: 'Chatbot Integration' },
  { value: 'Support Training Programs' },
  { value: 'Call Center Services' },
  { value: 'Client Feedback & Surveys' },
  { value: 'Community Management' },
  { value: 'Ticketing Systems' },
  { value: 'Customer Retention Strategies' },
  { value: 'Go-to-Market Strategy' },
  { value: 'Launch Event Planning' },
  { value: 'Product Demo Creation' },
  { value: 'Press Release Writing' },
  { value: 'Beta Testing Coordination' },
  { value: 'Early Adopter Outreach' },
  { value: 'Media Outreach and PR' },
  { value: 'Trade Show Support' },
  { value: 'Influencer Partnerships for Launch' },
  { value: 'Post-launch Support' },
  { value: 'Market Analysis & Research' },
  { value: 'Competitor Analysis' },
  { value: 'Customer Segmentation' },
  { value: 'Data Collection & Management' },
  { value: 'Predictive Analytics' },
  { value: 'A/B Testing' },
  { value: 'Data Visualization & Reporting' },
  { value: 'Business Intelligence Tools' },
  { value: 'User Analytics (Web, App)' },
  { value: 'KPI Tracking & Dashboards' },
  { value: 'Customer Journey Mapping' },
  { value: 'Feedback Loops & Surveys' },
  { value: 'Net Promoter Score (NPS) Programs' },
  { value: 'User Onboarding Tools' },
  { value: 'Loyalty Programs' },
  { value: 'Personalization & Targeting Strategies' },
  { value: 'Customer Success Management' },
  { value: 'Research & Development (R&D)' },
  { value: 'Patent Filing & Protection' },
  { value: 'Product Innovation Workshops' },
  { value: 'Feasibility Studies' },
  { value: 'Innovation Funding Programs' },
  { value: 'Sustainable Sourcing' },
  { value: 'Corporate Social Responsibility (CSR) Programs' },
  { value: 'Green Product Design' },
  { value: 'Carbon Footprint Reduction Initiatives' },
  { value: 'Energy Efficiency Solutions' },
  { value: 'Ethics & Compliance Programs' },
  { value: 'Vision & Mission Development' },
  { value: 'Cross-functional Collaboration' },
];

export const categories = [
  { value: 'Incubation' },
  { value: 'Acceleration Programs' },
  { value: 'Startup Guidance' },
  { value: 'MVP Creation' },
  { value: 'Website Creation' },
  { value: 'Marketing Support' },
  { value: 'Branding' },
  { value: 'Social Media Handling' },
  { value: 'Pitch Deck Expert' },
  { value: 'Pitch Deck Creation' },
  { value: 'Prototype Making (Digital)' },
  { value: 'Prototype Making (Hardware)' },
  { value: 'Coworking Space' },
  { value: 'Finance' },
  { value: 'Sales' },
  { value: 'Others' },
];

export const locations = [
  { value: 'Abohar, Punjab' },
  { value: 'Achalpur, Maharashtra' },
  { value: 'Adilabad, Andhra Pradesh' },
  { value: 'Adityapur, Jharkhand' },
  { value: 'Adoni, Andhra Pradesh' },
  { value: 'Agartala, Tripura' },
  { value: 'Agra, Uttar Pradesh' },
  { value: 'Ahmadabad, Gujarat' },
  { value: 'Ahmadnagar, Maharashtra' },
  { value: 'Aizawl, Mizoram' },
  { value: 'Ajmer, Rajasthan' },
  { value: 'Akbarpur, Uttar Pradesh' },
  { value: 'Akola, Maharashtra' },
  { value: 'Alandur, Tamil Nadu' },
  { value: 'Alappuzha, Kerala' },
  { value: 'Aligarh, Uttar Pradesh' },
  { value: 'Allahabad, Uttar Pradesh' },
  { value: 'Alwar, Rajasthan' },
  { value: 'Ambala, Haryana' },
  { value: 'Ambala Sadar, Haryana' },
  { value: 'Ambarnath, Maharashtra' },
  { value: 'Ambattur, Tamil Nadu' },
  { value: 'Ambikapur, Chhattisgarh' },
  { value: 'Ambur, Tamil Nadu' },
  { value: 'Amravati, Maharashtra' },
  { value: 'Amreli, Gujarat' },
  { value: 'Amritsar, Punjab' },
  { value: 'Amroha, Uttar Pradesh' },
  { value: 'Anand, Gujarat' },
  { value: 'Anantapur, Andhra Pradesh' },
  { value: 'Anantnag, Jammu & Kashmir' },
  { value: 'Arrah, Bihar' },
  { value: 'Asansol, West Bengal' },
  { value: 'Ashoknagar Kalyangarh, West Bengal' },
  { value: 'Aurangabad, Bihar' },
  { value: 'Aurangabad, Maharashtra' },
  { value: 'Avadi, Tamil Nadu' },
  { value: 'Azamgarh, Uttar Pradesh' },
  { value: 'Badlapur, Maharashtra' },
  { value: 'Bagaha, Bihar' },
  { value: 'Bagalkot, Karnataka' },
  { value: 'Bahadurgarh, Haryana' },
  { value: 'Baharampur, West Bengal' },
  { value: 'Bahraich, Uttar Pradesh' },
  { value: 'Baidyabati, West Bengal' },
  { value: 'Baleshwar Town, Orissa' },
  { value: 'Ballia, Uttar Pradesh' },
  { value: 'Bally, West Bengal' },
  { value: 'Bally City, West Bengal' },
  { value: 'Balurghat, West Bengal' },
  { value: 'Banda, Uttar Pradesh' },
  { value: 'Bankura, West Bengal' },
  { value: 'Bansberia, West Bengal' },
  { value: 'Banswara, Rajasthan' },
  { value: 'Baran, Rajasthan' },
  { value: 'Baranagar, West Bengal' },
  { value: 'Barasat, West Bengal' },
  { value: 'Baraut, Uttar Pradesh' },
  { value: 'Barddhaman, West Bengal' },
  { value: 'Bareilly, Uttar Pradesh' },
  { value: 'Baripada Town, Orissa' },
  { value: 'Barnala, Punjab' },
  { value: 'Barrackpur, West Bengal' },
  { value: 'Barshi, Maharashtra' },
  { value: 'Basirhat, West Bengal' },
  { value: 'Basti, Uttar Pradesh' },
  { value: 'Batala, Punjab' },
  { value: 'Bathinda, Punjab' },
  { value: 'Beawar, Rajasthan' },
  { value: 'Begusarai, Bihar' },
  { value: 'Belgaum, Karnataka' },
  { value: 'Bellary, Karnataka' },
  { value: 'Bengaluru, Karnataka' },
  { value: 'Bettiah, Bihar' },
  { value: 'Betul, Madhya Pradesh' },
  { value: 'Bhadrak, Orissa' },
  { value: 'Bhadravati, Karnataka' },
  { value: 'Bhadreswar, West Bengal' },
  { value: 'Bhagalpur, Bihar' },
  { value: 'Bhalswa Jahangir Pur, Nct Of Delhi' },
  { value: 'Bharatpur, Rajasthan' },
  { value: 'Bharuch, Gujarat' },
  { value: 'Bhatpara, West Bengal' },
  { value: 'Bhavnagar, Gujarat' },
  { value: 'Bhilai Nagar, Chhattisgarh' },
  { value: 'Bhilwara, Rajasthan' },
  { value: 'Bhimavaram, Andhra Pradesh' },
  { value: 'Bhind, Madhya Pradesh' },
  { value: 'Bhiwadi, Rajasthan' },
  { value: 'Bhiwandi, Maharashtra' },
  { value: 'Bhiwani, Haryana' },
  { value: 'Bhopal, Madhya Pradesh' },
  { value: 'Bhubaneswar Town, Orissa' },
  { value: 'Bhuj, Gujarat' },
  { value: 'Bhusawal, Maharashtra' },
  { value: 'Bid, Maharashtra' },
  { value: 'Bidar, Karnataka' },
  { value: 'Bidhan Nagar, West Bengal' },
  { value: 'Biharsharif, Bihar' },
  { value: 'Bijapur, Karnataka' },
  { value: 'Bikaner, Rajasthan' },
  { value: 'Bilaspur, Chhattisgarh' },
  { value: 'Bokaro Steel City, Jharkhand' },
  { value: 'Bongaon, West Bengal' },
  { value: 'Botad, Gujarat' },
  { value: 'Brahmapur Town, Orissa' },
  { value: 'Budaun, Uttar Pradesh' },
  { value: 'Bulandshahr, Uttar Pradesh' },
  { value: 'Bundi, Rajasthan' },
  { value: 'Burari, Nct Of Delhi' },
  { value: 'Burhanpur, Madhya Pradesh' },
  { value: 'Buxar, Bihar' },
  { value: 'Champdani, West Bengal' },
  { value: 'Chandannagar, West Bengal' },
  { value: 'Chandausi, Uttar Pradesh' },
  { value: 'Chandigarh, Chandigarh' },
  { value: 'Chandrapur, Maharashtra' },
  { value: 'Chapra, Bihar' },
  { value: 'Chas, Jharkhand' },
  { value: 'Chennai, Tamil Nadu' },
  { value: 'Chhattarpur, Madhya Pradesh' },
  { value: 'Chhindwara, Madhya Pradesh' },
  { value: 'Chikmagalur, Karnataka' },
  { value: 'Chilakaluripet, Andhra Pradesh' },
  { value: 'Chitradurga, Karnataka' },
  { value: 'Chittaurgarh, Rajasthan' },
  { value: 'Chittoor, Andhra Pradesh' },
  { value: 'Churu, Rajasthan' },
  { value: 'Coimbatore, Tamil Nadu' },
  { value: 'Cuddalore, Tamil Nadu' },
  { value: 'Cuttack, Orissa' },
  { value: 'Dabgram, West Bengal' },
  { value: 'Dallo Pura, Nct Of Delhi' },
  { value: 'Damoh, Madhya Pradesh' },
  { value: 'Darbhanga, Bihar' },
  { value: 'Darjiling, West Bengal' },
  { value: 'Datia, Madhya Pradesh' },
  { value: 'Davanagere, Karnataka' },
  { value: 'Deesa, Gujarat' },
  { value: 'Dehradun, Uttarakhand' },
  { value: 'Dehri, Bihar' },
  { value: 'Delhi, Nct Of Delhi' },
  { value: 'Delhi Cantonment, Nct Of Delhi' },
  { value: 'Deoghar, Jharkhand' },
  { value: 'Deoli, Nct Of Delhi' },
  { value: 'Deoria, Uttar Pradesh' },
  { value: 'Dewas, Madhya Pradesh' },
  { value: 'Dhanbad, Jharkhand' },
  { value: 'Dharmavaram, Andhra Pradesh' },
  { value: 'Dhaulpur, Rajasthan' },
  { value: 'Dhule, Maharashtra' },
  { value: 'Dibrugarh, Assam' },
  { value: 'Dimapur, Nagaland' },
  { value: 'Dinapur Nizamat, Bihar' },
  { value: 'Dindigul, Tamil Nadu' },
  { value: 'Dum Dum, West Bengal' },
  { value: 'Durg, Chhattisgarh' },
  { value: 'Durgapur, West Bengal' },
  { value: 'Eluru, Andhra Pradesh' },
  { value: 'Erode, Tamil Nadu' },
  { value: 'Etah, Uttar Pradesh' },
  { value: 'Etawah, Uttar Pradesh' },
  { value: 'Faizabad, Uttar Pradesh' },
  { value: 'Faridabad, Haryana' },
  { value: 'Farrukhabad, Uttar Pradesh' },
  { value: 'Fatehpur, Uttar Pradesh' },
  { value: 'Firozabad, Uttar Pradesh' },
  { value: 'Gadag-Betageri, Karnataka' },
  { value: 'Gandhidham, Gujarat' },
  { value: 'Gandhinagar, Gujarat' },
  { value: 'Gangapur City, Rajasthan' },
  { value: 'Ganjbasoda, Madhya Pradesh' },
  { value: 'Gaya, Bihar' },
  { value: 'Ghaziabad, Uttar Pradesh' },
  { value: 'Giridih, Jharkhand' },
  { value: 'Goalpara, Assam' },
  { value: 'Gobindgarh, Punjab' },
  { value: 'Gobindgarh, Punjab' },
  { value: 'Godhra, Gujarat' },
  { value: 'Gohana, Haryana' },
  { value: 'Gokak, Karnataka' },
  { value: 'Gondiya, Maharashtra' },
  { value: 'Gopalpur, West Bengal' },
  { value: 'Gorakhpur, Uttar Pradesh' },
  { value: 'Gudivada, Andhra Pradesh' },
  { value: 'Gulbarga, Karnataka' },
  { value: 'Guna, Madhya Pradesh' },
  { value: 'Guntakal, Andhra Pradesh' },
  { value: 'Guntur, Andhra Pradesh' },
  { value: 'Gurgaon, Haryana' },
  { value: 'Guwahati, Assam' },
  { value: 'Gwalior, Madhya Pradesh' },
  { value: 'Habra, West Bengal' },
  { value: 'Hajipur, Bihar' },
  { value: 'Haldia, West Bengal' },
  { value: 'Haldwani-cum-Kathgodam, Uttarakhand' },
  { value: 'Halisahar, West Bengal' },
  { value: 'Hamirpur, Uttar Pradesh' },
  { value: 'Hanumangarh, Rajasthan' },
  { value: 'Hapur, Uttar Pradesh' },
  { value: 'Hardoi, Uttar Pradesh' },
  { value: 'Haridwar, Uttarakhand' },
  { value: 'Hazaribag, Jharkhand' },
  { value: 'Hindupur, Andhra Pradesh' },
  { value: 'Hinganghat, Maharashtra' },
  { value: 'Hisar, Haryana' },
  { value: 'Hoshiarpur, Punjab' },
  { value: 'Hospet, Karnataka' },
  { value: 'Howrah, West Bengal' },
  { value: 'Hubli-Dharwad, Karnataka' },
  { value: 'Hugli-Chinsurah, West Bengal' },
  { value: 'Hyderabad, Andhra Pradesh' },
  { value: 'Ichalkaranji, Maharashtra' },
  { value: 'Imphal, Manipur' },
  { value: 'Indore, Madhya Pradesh' },
  { value: 'Itarsi, Madhya Pradesh' },
  { value: 'Jabalpur, Madhya Pradesh' },
  { value: 'Jagadhri, Haryana' },
  { value: 'Jagtial, Andhra Pradesh' },
  { value: 'Jaipur, Rajasthan' },
  { value: 'Jalandhar, Punjab' },
  { value: 'Jalgaon, Maharashtra' },
  { value: 'Jalna, Maharashtra' },
  { value: 'Jamalpur, Bihar' },
  { value: 'Jammu, Jammu & Kashmir' },
  { value: 'Jamnagar, Gujarat' },
  { value: 'Jamshedpur, Jharkhand' },
  { value: 'Jamuria, West Bengal' },
  { value: 'Jaunpur, Uttar Pradesh' },
  { value: 'Jehanabad, Bihar' },
  { value: 'Jetpur Navagadh, Gujarat' },
  { value: 'Jind, Haryana' },
  { value: 'Jodhpur, Rajasthan' },
  { value: 'Junagadh, Gujarat' },
  { value: 'Kadapa, Andhra Pradesh' },
  { value: 'Kaithal, Haryana' },
  { value: 'Kakinada, Andhra Pradesh' },
  { value: 'Kalol, Gujarat' },
  { value: 'Kalyan-Dombivali, Maharashtra' },
  { value: 'Kamarhati, West Bengal' },
  { value: 'Kamrup, Assam' },
  { value: 'Kanpur, Uttar Pradesh' },
  { value: 'Kapurthala, Punjab' },
  { value: 'Karawal Nagar, Nct Of Delhi' },
  { value: 'Karauli, Rajasthan' },
  { value: 'Karimnagar, Andhra Pradesh' },
  { value: 'Karnal, Haryana' },
  { value: 'Karnul, Andhra Pradesh' },
  { value: 'Katihar, Bihar' },
  { value: 'Kavali, Andhra Pradesh' },
  { value: 'Kavaratti, Lakshadweep' },
  { value: 'Kayamkulam, Kerala' },
  { value: 'Kendrapara, Orissa' },
  { value: 'Kendujhar, Orissa' },
  { value: 'Keshod, Gujarat' },
  { value: 'Kharagpur, West Bengal' },
  { value: 'Khatauli, Uttar Pradesh' },
  { value: 'Khora, Uttar Pradesh' },
  { value: 'Kishanganj, Bihar' },
  { value: 'Kishangarh, Rajasthan' },
  { value: 'Kochi, Kerala' },
  { value: 'Kolar, Karnataka' },
  { value: 'Kolhapur, Maharashtra' },
  { value: 'Kolkata, West Bengal' },
  { value: 'Kollam, Kerala' },
  { value: 'Korba, Chhattisgarh' },
  { value: 'Kota, Rajasthan' },
  { value: 'Kottayam, Kerala' },
  { value: 'Kozhikode, Kerala' },
  { value: 'Krishnanagar, West Bengal' },
  { value: 'Kulti, West Bengal' },
  { value: 'Kumbakonam, Tamil Nadu' },
  { value: 'Kurnool, Andhra Pradesh' },
  { value: 'Kurukshetra, Haryana' },
  { value: 'Lakhimpur, Uttar Pradesh' },
  { value: 'Lalitpur, Uttar Pradesh' },
  { value: 'Latur, Maharashtra' },
  { value: 'Loni, Uttar Pradesh' },
  { value: 'Lucknow, Uttar Pradesh' },
  { value: 'Ludhiana, Punjab' },
  { value: 'Machilipatnam, Andhra Pradesh' },
  { value: 'Madanapalle, Andhra Pradesh' },
  { value: 'Madhyamgram, West Bengal' },
  { value: 'Madurai, Tamil Nadu' },
  { value: 'Mahbubnagar, Andhra Pradesh' },
  { value: 'Mahesana, Gujarat' },
  { value: 'Maheshtala, West Bengal' },
  { value: 'Mainpuri, Uttar Pradesh' },
  { value: 'Malappuram, Kerala' },
  { value: 'Malegaon, Maharashtra' },
  { value: 'Malerkotla, Punjab' },
  { value: 'Malkajgiri, Andhra Pradesh' },
  { value: 'Malout, Punjab' },
  { value: 'Mancherial, Andhra Pradesh' },
  { value: 'Mandasor, Madhya Pradesh' },
  { value: 'Mandya, Karnataka' },
  { value: 'Mangalore, Karnataka' },
  { value: 'Mango, Jharkhand' },
  { value: 'Mangu, Madhya Pradesh' },
  { value: 'Mathura, Uttar Pradesh' },
  { value: 'Medinipur, West Bengal' },
  { value: 'Meerut, Uttar Pradesh' },
  { value: 'Mira-Bhayandar, Maharashtra' },
  { value: 'Mirzapur, Uttar Pradesh' },
  { value: 'Modinagar, Uttar Pradesh' },
  { value: 'Moga, Punjab' },
  { value: 'Moradabad, Uttar Pradesh' },
  { value: 'Morena, Madhya Pradesh' },
  { value: 'Motihari, Bihar' },
  { value: 'Muktsar, Punjab' },
  { value: 'Mumbai, Maharashtra' },
  { value: 'Munger, Bihar' },
  { value: 'Muradnagar, Uttar Pradesh' },
  { value: 'Mysore, Karnataka' },
  { value: 'Nadiad, Gujarat' },
  { value: 'Nagaon, Assam' },
  { value: 'Nagercoil, Tamil Nadu' },
  { value: 'Nagpur, Maharashtra' },
  { value: 'Naihati, West Bengal' },
  { value: 'Nanded-Waghala, Maharashtra' },
  { value: 'Nandurbar, Maharashtra' },
  { value: 'Nandyal, Andhra Pradesh' },
  { value: 'Narasaraopet, Andhra Pradesh' },
  { value: 'Nashik, Maharashtra' },
  { value: 'Navi Mumbai, Maharashtra' },
  { value: 'Neemuch, Madhya Pradesh' },
  { value: 'Nellore, Andhra Pradesh' },
  { value: 'New Delhi, Delhi' },
  { value: 'Nizamabad, Andhra Pradesh' },
  { value: 'Noida, Uttar Pradesh' },
  { value: 'North Dumdum, West Bengal' },
  { value: 'Ongole, Andhra Pradesh' },
  { value: 'Orai, Uttar Pradesh' },
  { value: 'Osmanabad, Maharashtra' },
  { value: 'Pallavaram, Tamil Nadu' },
  { value: 'Panaji, Goa' },
  { value: 'Panipat, Haryana' },
  { value: 'Panvel, Maharashtra' },
  { value: 'Parbhani, Maharashtra' },
  { value: 'Patan, Gujarat' },
  { value: 'Pathankot, Punjab' },
  { value: 'Patiala, Punjab' },
  { value: 'Patna, Bihar' },
  { value: 'Pilibhit, Uttar Pradesh' },
  { value: 'Pimpri-Chinchwad, Maharashtra' },
  { value: 'Pondicherry, Puducherry' },
  { value: 'Port Blair, Andaman & Nicobar Islands' },
  { value: 'Proddatur, Andhra Pradesh' },
  { value: 'Pudukkottai, Tamil Nadu' },
  { value: 'Pune, Maharashtra' },
  { value: 'Puri, Odisha' },
  { value: 'Raebareli, Uttar Pradesh' },
  { value: 'Raichur, Karnataka' },
  { value: 'Raiganj, West Bengal' },
  { value: 'Raigarh, Chhattisgarh' },
  { value: 'Raipur, Chhattisgarh' },
  { value: 'Rajahmundry, Andhra Pradesh' },
  { value: 'Rajapalayam, Tamil Nadu' },
  { value: 'Rajauli, Bihar' },
  { value: 'Rajgarh, Madhya Pradesh' },
  { value: 'Rajkot, Gujarat' },
  { value: 'Rajnandgaon, Chhattisgarh' },
  { value: 'Rajpipla, Gujarat' },
  { value: 'Rajsamand, Rajasthan' },
  { value: 'Ramgarh, Jharkhand' },
  { value: 'Rampur, Uttar Pradesh' },
  { value: 'Ranchi, Jharkhand' },
  { value: 'Ranibennur, Karnataka' },
  { value: 'Ratlam, Madhya Pradesh' },
  { value: 'Rewa, Madhya Pradesh' },
  { value: 'Rohtak, Haryana' },
  { value: 'Roorkee, Uttarakhand' },
  { value: 'Rourkela, Odisha' },
  { value: 'Rudrapur, Uttarakhand' },
  { value: 'Sagar, Madhya Pradesh' },
  { value: 'Saharanpur, Uttar Pradesh' },
  { value: 'Salem, Tamil Nadu' },
  { value: 'Sambalpur, Odisha' },
  { value: 'Sambhal, Uttar Pradesh' },
  { value: 'Sangli-Miraj-Kupwad, Maharashtra' },
  { value: 'Santipur, West Bengal' },
  { value: 'Sasaram, Bihar' },
  { value: 'Satara, Maharashtra' },
  { value: 'Satna, Madhya Pradesh' },
  { value: 'Sawai Madhopur, Rajasthan' },
  { value: 'Secunderabad, Telangana' },
  { value: 'Serampore, West Bengal' },
  { value: 'Shillong, Meghalaya' },
  { value: 'Shimla, Himachal Pradesh' },
  { value: 'Shimoga, Karnataka' },
  { value: 'Shivpuri, Madhya Pradesh' },
  { value: 'Sikar, Rajasthan' },
  { value: 'Silchar, Assam' },
  { value: 'Siliguri, West Bengal' },
  { value: 'Singrauli, Madhya Pradesh' },
  { value: 'Sirsa, Haryana' },
  { value: 'Sitapur, Uttar Pradesh' },
  { value: 'Siwan, Bihar' },
  { value: 'Solapur, Maharashtra' },
  { value: 'Sonipat, Haryana' },
  { value: 'South Dumdum, West Bengal' },
  { value: 'Srikakulam, Andhra Pradesh' },
  { value: 'Srinagar, Jammu & Kashmir' },
  { value: 'Sultanpur, Uttar Pradesh' },
  { value: 'Surat, Gujarat' },
  { value: 'Surendranagar Dudhrej, Gujarat' },
  { value: 'Suri, West Bengal' },
  { value: 'Tadepalligudem, Andhra Pradesh' },
  { value: 'Tadpatri, Andhra Pradesh' },
  { value: 'Tamluk, West Bengal' },
  { value: 'Tarn Taran Sahib, Punjab' },
  { value: 'Tenali, Andhra Pradesh' },
  { value: 'Thanjavur, Tamil Nadu' },
  { value: 'Theni, Tamil Nadu' },
  { value: 'Thiruvananthapuram, Kerala' },
  { value: 'Thoubal, Manipur' },
  { value: 'Thrissur, Kerala' },
  { value: 'Tinsukia, Assam' },
  { value: 'Tirunelveli, Tamil Nadu' },
  { value: 'Tirupati, Andhra Pradesh' },
  { value: 'Tirupur, Tamil Nadu' },
  { value: 'Tiruvottiyur, Tamil Nadu' },
  { value: 'Tumkur, Karnataka' },
  { value: 'Udaipur, Rajasthan' },
  { value: 'Udgir, Maharashtra' },
  { value: 'Ujjain, Madhya Pradesh' },
  { value: 'Ulhasnagar, Maharashtra' },
  { value: 'Uluberia, West Bengal' },
  { value: 'Unnao, Uttar Pradesh' },
  { value: 'Uppal Kalan, Andhra Pradesh' },
  { value: 'Uttarpara-Kotrung, West Bengal' },
  { value: 'Vadodara, Gujarat' },
  { value: 'Vallabh Vidyanagar, Gujarat' },
  { value: 'Valsad, Gujarat' },
  { value: 'Vapi, Gujarat' },
  { value: 'Varanasi, Uttar Pradesh' },
  { value: 'Vasai-Virar, Maharashtra' },
  { value: 'Vellore, Tamil Nadu' },
  { value: 'Veraval, Gujarat' },
  { value: 'Vijayawada, Andhra Pradesh' },
  { value: 'Visakhapatnam, Andhra Pradesh' },
  { value: 'Vizianagaram, Andhra Pradesh' },
  { value: 'Warangal, Telangana' },
  { value: 'Wardha, Maharashtra' },
  { value: 'Washim, Maharashtra' },
  { value: 'Yavatmal, Maharashtra' },
];

export const countryCodes = [
  { value: 'United States (+1)' },
  { value: 'Russia (+7)' },
  { value: 'Egypt (+20)' },
  { value: 'South Africa (+27)' },
  { value: 'Greece (+30)' },
  { value: 'Netherlands (+31)' },
  { value: 'Belgium (+32)' },
  { value: 'France (+33)' },
  { value: 'Spain (+34)' },
  { value: 'Hungary (+36)' },
  { value: 'Italy (+39)' },
  { value: 'Switzerland (+41)' },
  { value: 'Austria (+43)' },
  { value: 'United Kingdom (+44)' },
  { value: 'Denmark (+45)' },
  { value: 'Sweden (+46)' },
  { value: 'Norway (+47)' },
  { value: 'Poland (+48)' },
  { value: 'Germany (+49)' },
  { value: 'Peru (+51)' },
  { value: 'Mexico (+52)' },
  { value: 'Cuba (+53)' },
  { value: 'Argentina (+54)' },
  { value: 'Brazil (+55)' },
  { value: 'Chile (+56)' },
  { value: 'Colombia (+57)' },
  { value: 'Venezuela (+58)' },
  { value: 'Malaysia (+60)' },
  { value: 'Australia (+61)' },
  { value: 'Indonesia (+62)' },
  { value: 'Philippines (+63)' },
  { value: 'New Zealand (+64)' },
  { value: 'Singapore (+65)' },
  { value: 'Thailand (+66)' },
  { value: 'Japan (+81)' },
  { value: 'South Korea (+82)' },
  { value: 'Vietnam (+84)' },
  { value: 'China (+86)' },
  { value: 'Turkey (+90)' },
  { value: 'India (+91)' },
  { value: 'Pakistan (+92)' },
  { value: 'Afghanistan (+93)' },
  { value: 'Sri Lanka (+94)' },
  { value: 'Myanmar (+95)' },
  { value: 'Maldives (+960)' },
  { value: 'Lebanon (+961)' },
  { value: 'Jordan (+962)' },
  { value: 'Syria (+963)' },
  { value: 'Iraq (+964)' },
  { value: 'Kuwait (+965)' },
  { value: 'Saudi Arabia (+966)' },
  { value: 'Yemen (+967)' },
  { value: 'Oman (+968)' },
  { value: 'Palestine (+970)' },
  { value: 'United Arab Emirates (+971)' },
  { value: 'Israel (+972)' },
  { value: 'Bahrain (+973)' },
  { value: 'Qatar (+974)' },
  { value: 'Bhutan (+975)' },
  { value: 'Mongolia (+976)' },
  { value: 'Nepal (+977)' },
  { value: 'Tajikistan (+992)' },
  { value: 'Turkmenistan (+993)' },
  { value: 'Azerbaijan (+994)' },
  { value: 'Georgia (+995)' },
  { value: 'Kyrgyzstan (+996)' },
  { value: 'Uzbekistan (+998)' },
  { value: 'Ethiopia (+251)' },
  { value: 'Somalia (+252)' },
  { value: 'Djibouti (+253)' },
  { value: 'Kenya (+254)' },
  { value: 'Tanzania (+255)' },
  { value: 'Uganda (+256)' },
  { value: 'Burundi (+257)' },
  { value: 'Mozambique (+258)' },
  { value: 'Zambia (+260)' },
  { value: 'Madagascar (+261)' },
  { value: 'Réunion (+262)' },
  { value: 'Zimbabwe (+263)' },
  { value: 'Namibia (+264)' },
  { value: 'Malawi (+265)' },
  { value: 'Lesotho (+266)' },
  { value: 'Botswana (+267)' },
  { value: 'Eswatini (+268)' },
  { value: 'Comoros (+269)' },
  { value: 'Saint Helena (+290)' },
  { value: 'Eritrea (+291)' },
  { value: 'Aruba (+297)' },
  { value: 'Faroe Islands (+298)' },
  { value: 'Greenland (+299)' },
];

export const industries = [
  { value: 'Advertising' },
  { value: 'Agriculture' },
  { value: 'AI (Artificial Intelligence)' },
  { value: 'Analytics' },
  { value: 'AR/VR (Augmented Reality/Virtual Reality)' },
  { value: 'Automotive' },
  { value: 'Banking' },
  { value: 'Construction' },
  { value: 'Consumer Goods' },
  { value: 'Dating/Social Networking' },
  { value: 'Design' },
  { value: 'Education' },
  { value: 'Energy & Utilities' },
  { value: 'Enterprise Software' },
  { value: 'Events' },
  { value: 'Fashion' },
  { value: 'Finance Technology' },
  { value: 'Food & Beverages' },
  { value: 'Gaming' },
  { value: 'Healthcare & Lifesciences' },
  { value: 'Human Resources' },
  { value: 'IT Services' },
  { value: 'Logistics' },
  { value: 'Manufacturing' },
  { value: 'Media & Entertainment' },
  { value: 'Nanotechnology' },
  { value: 'Retail' },
  { value: 'Robotics' },
  { value: 'Security' },
  { value: 'Sports' },
  { value: 'Telecommunications' },
  { value: 'Textiles & Apparel' },
  { value: 'Transportation' },
  { value: 'Travel & Tourism' },
  { value: 'Waste Management' },
  { value: 'Water Management' },
  { value: 'Others' },
];

export const sectors = [
  { value: 'Digital Advertising' },
  { value: 'Print Advertising' },
  { value: 'Media Buying' },
  { value: 'Agri-Tech' },
  { value: 'Farming' },
  { value: 'Organic Farming' },
  { value: 'Machine Learning' },
  { value: 'Robotics' },
  { value: 'Natural Language Processing' },
  { value: 'Data Analytics' },
  { value: 'Big Data' },
  { value: 'Predictive Analytics' },
  { value: 'Virtual Reality Hardware' },
  { value: 'Augmented Reality Software' },
  { value: 'Mixed Reality' },
  { value: 'Electric Vehicles' },
  { value: 'Vehicle Maintenance' },
  { value: 'Car Rentals' },
  { value: 'Digital Banking' },
  { value: 'FinTech' },
  { value: 'Neobanking' },
  { value: 'Construction Tech' },
  { value: 'Smart Buildings' },
  { value: 'Real Estate Development' },
  { value: 'Fast Moving Consumer Goods (FMCG)' },
  { value: 'Consumer Electronics' },
  { value: 'Household Products' },
  { value: 'Online Dating Platforms' },
  { value: 'Social Media Applications' },
  { value: 'Community Building Platforms' },
  { value: 'Graphic Design' },
  { value: 'Industrial Design' },
  { value: 'UX/UI Design' },
  { value: 'EdTech' },
  { value: 'Online Tutoring' },
  { value: 'Educational Content' },
  { value: 'Renewable Energy' },
  { value: 'Smart Grids' },
  { value: 'Energy Storage' },
  { value: 'Business Management Software' },
  { value: 'Customer Relationship Management (CRM)' },
  { value: 'Enterprise Resource Planning (ERP)' },
  { value: 'Event Management' },
  { value: 'Virtual Events' },
  { value: 'Ticketing Solutions' },
  { value: 'Fashion Tech' },
  { value: 'Online Fashion Retail' },
  { value: 'Sustainable Fashion' },
  { value: 'Payment Solutions' },
  { value: 'Personal Finance Management' },
  { value: 'Cryptocurrency' },
  { value: 'Food Delivery' },
  { value: 'Restaurant Tech' },
  { value: 'Packaged Foods' },
  { value: 'Mobile Games' },
  { value: 'eSports' },
  { value: 'Game Development' },
  { value: 'HealthTech' },
  { value: 'Biotechnology' },
  { value: 'Medical Devices' },
  { value: 'HR Tech' },
  { value: 'Recruitment Platforms' },
  { value: 'Employee Engagement' },
  { value: 'Cloud Computing' },
  { value: 'IT Consulting' },
  { value: 'Supply Chain Management' },
  { value: 'Freight Services' },
  { value: 'Last-Mile Delivery' },
  { value: 'Smart Manufacturing' },
  { value: 'Industrial IoT' },
  { value: '3D Printing' },
  { value: 'Digital Media' },
  { value: 'Content Creation' },
  { value: 'OTT Platforms' },
  { value: 'Nano-Materials' },
  { value: 'Nano-Medicine' },
  { value: 'Nano-Devices' },
  { value: 'E-Commerce' },
  { value: 'Brick-and-Mortar Retail' },
  { value: 'Retail Tech' },
  { value: 'Industrial Robots' },
  { value: 'Service Robots' },
  { value: 'Robotic Process Automation (RPA)' },
  { value: 'Physical Security' },
  { value: 'Cybersecurity' },
  { value: 'Surveillance Systems' },
  { value: 'Sports Tech' },
  { value: 'Fitness Tech' },
  { value: 'Sports Analytics' },
  { value: 'Telecom Services' },
  { value: 'Network Equipment' },
  { value: 'IoT Connectivity' },
  { value: 'Textile Manufacturing' },
  { value: 'Apparel Design' },
  { value: 'Smart Textiles' },
  { value: 'Ride-Sharing' },
  { value: 'Fleet Management' },
  { value: 'Public Transport Solutions' },
  { value: 'Travel Tech' },
  { value: 'Tourism Services' },
  { value: 'Hospitality Tech' },
  { value: 'Recycling Solutions' },
  { value: 'Waste-to-Energy' },
  { value: 'E-Waste Management' },
  { value: 'Water Purification' },
  { value: 'Smart Water Systems' },
  { value: 'Water Conservation Technologies' },
  { value: 'Others' },
];

export const trlLevels = [
  { value: 'TRL 1: Basic Research' },
  { value: 'TRL 2: Applied Research' },
  { value: 'TRL 3: Critical Function or Proof of Concept Established' },
  {
    value: 'TRL 4: Lab Testing/Validation of Alpha Prototype Component/Process',
  },
  { value: 'TRL 5: Laboratory Testing of Integrated/Semi-Integrated System' },
  { value: 'TRL 6: Prototype System Verified' },
  { value: 'TRL 7: Integrated Pilot System Demonstrated' },
  { value: 'TRL 8: System Incorporated in Commercial Design' },
  { value: 'TRL 9: System Proven and Ready for Full Commercial Deployment' },
];

export const productStages = [
  { value: 'Ideation' },
  { value: 'Minimum Viable Product (MVP)' },
  { value: 'Product-Market Fit (PMF)' },
  { value: 'Go-to-Market' },
  { value: 'Growth and Scale' },
];

export const fundingStages = [
  { value: 'Pre-seed' },
  { value: 'Seed' },
  { value: 'Series A' },
  { value: 'Series B' },
  { value: 'Series C' },
  { value: 'Series C+' },
];
