const opportunities = [
  {
    id: "e4c22bc5-4c06-4888-b75c-783db74eb15d",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title:
      "Samvardhan: Physical Product Design Accelerator for Healthcare Innovation",
    websiteUrl: "http://pieds-bitspilani.org/",
    fundingAmount: null,
    targetIndustry: "Healthcare & Lifesciences ",
    targetSector: "HealthTech",
    targetWomenFounder: null,
    targetProductStage: [
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
    ],
    targetFundingStage: ["Pre-Seed", "Seed"],
    description:
      "Are you building a healthcare or medical device startup and need support in transforming your prototype into a market-ready product? Samvardhan, a one-of-its-kind product design accelerator, is now accepting applications!\n\nSamvardhan brings together four powerful partners:\n\n* PIEDS : Pilani Innovation & Entrepreneurship Development Society, BITS Pilani with its proven track record in startup incubation and mentorship\n* Studio Carbon, bringing cutting-edge design expertise in healthcare and deep tech innovation\n* Biotechnology Industry Research Assistance Council (BIRAC) (Biotechnology Industry Research Assistance Council), a GOI enterprise offering biotech ecosystem support\n* Birla Carbon is one of the world's largest manufacturer and supplier of high-quality carbon black\n\nWhat you get:\n\n* ₹10 Lakhs funding to accelerate your product development\n* 100 hours of specialized design consultation from Studio Carbon experts\n* Access to state-of-the-art prototyping facilities\n* Intensive bootcamps at Studio Carbon and BITS Pilani\n* User research and field testing support through BITS Design School Mumbai\n* Mentorship from industry experts and successful founders\n* Access to BIRAC's extensive biotech network and resources",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdu5haCv2stU_29mOgOziVhZLzcCG6bweFon7dDb_hCXzWdbw/viewform",
    userId: null,
  },
  {
    id: "41a784d6-7462-400f-a3d0-15fae91d5254",
    imageUrl: null,
    type: "Funding",
    subtype: "Equity",
    title: "BIRAC's SEED and LEAP programs",
    websiteUrl: "https://fitt-iitd.in/web/home",
    fundingAmount: null,
    targetIndustry: "Healthcare & Lifesciences",
    targetSector: "HealthTech, Biotechnology ",
    targetWomenFounder: null,
    targetProductStage: [
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
    ],
    targetFundingStage: ["Pre-Seed", "Seed"],
    description:
      "FITT present a unique investment opportunity through the SEED & LEAP Fund, an initiative by Biotechnology Industry Research Assistance Council (BIRAC). This funding aims to support innovative startups in the biotechnology sector, providing crucial financial assistance to foster sustainable enterprise development. The proposed funding support is positioned to act as a catalyst in bringing technologies/ products forward towards piloting/ commercialization and reducing their gestation to commercialization.\n\nWhat Fund Offers: \n\nEquity Linked Investment up to 30 lakhs under SEED and 1 cr under LEAP\nDedicated Co-Working and Lab Facilities\nGuidance from Technical and Business Experts\nAccess to Regulatory and Clinical Support\nIP Management and Support\nCollaboration with Industry Players\nAccess to Investors\nEligibility Criteria:\nStart-up venturing into the domain of Healthcare / Biotechnology / Bioprinting / Diagnostics / Personalized Medicines / Tissues Engineering / Biopharma / Pharma with a focus on developing novel products.\nMore than 51% of the shares are held by resident Indian individuals.\nSEED is open for any startup — incubated or non-incubated     \nLEAP is open for any startup — incubated or non-incubated — that are actively raising funds to scale and grow.\n\nSelection Criteria\n\nFocus on innovative, product-oriented technologies with a strong IP potential\nAddress an unmet need with significant market potential\nHave a strong technical and business understanding \nDemonstrate a clear market strategy and understanding of end-users\nFor start-ups having strong business growth potential along with clear revenue and growth model.\n\nNote: Only startup can apply (Mandatory to be registered as a Private Limited Company)",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://docs.google.com/forms/d/e/1FAIpQLScA64oaXWMcm1lJjsfvxXyfePQ_Uzlew-lD2GIG1wl6WJOzHw/viewform",
    userId: null,
  },
  {
    id: "4fb21fc3-e945-4384-9633-c5d5148792c6",
    imageUrl: null,
    type: "Funding",
    subtype: "Equity",
    title: "GRIP 3.0",
    websiteUrl: "https://pscst.punjab.gov.in/en/grip",
    fundingAmount: null,
    targetIndustry: "",
    targetSector: "",
    targetWomenFounder: null,
    targetProductStage: ["Ideation", "Minimum viable product (MVP)"],
    targetFundingStage: ["Pre-Seed"],
    description:
      "Punjab State Council of Science and Technology (PSCST) in collaboration with ACIC RISE Association, Chandigarh Engineering College-CGC Landran is selecting grassroots innovators of Punjab. The top ideas will be awarded with the cash prizes. Apart from this, the selected ideas would get an opportunity for IP Protection, Showcase at National & State Level, Linkage for Validation & Scale-up and to be incubated with ACIC RISE. \nNo Registration Fees",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink: "https://bit.ly/3XdF6Ag",
    userId: null,
  },
  {
    id: "b3d1d88b-c30e-4836-b85b-3b98b691ea93",
    imageUrl: null,
    type: "Funding",
    subtype: "Equity",
    title: "inFINity 2.0",
    websiteUrl: "https://www.infinitynow.tech/",
    fundingAmount: null,
    targetIndustry: "Banking",
    targetSector: "FinTech",
    targetWomenFounder: null,
    targetProductStage: [
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
    ],
    targetFundingStage: ["Pre-Seed", "Seed", "Series A"],
    description:
      "Calling all Fintech Founders!\n\nAfter a groundbreaking first edition with 400+ applications & 30 game-changing startups, inFINity 2.0 is back—bigger, better & more impactful than ever!\n\nWhat’s new in inFINity 2.0?\n\nUp to $5M investment available for eligible startups\nAWS Activate Credits & up to $100K PayU Startup Program credits\nA 12-week hybrid accelerator with masterclasses, mentorship & fundraising support\nExclusive access to Prosus & top-tier investors to accelerate your growth\n\n\nRegister now & take your fintech startup to the next level with inFINity 2.0!",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink: "https://www.infinitynow.tech/",
    userId: null,
  },
  {
    id: "0bf7d9ba-4251-478f-b700-4c0ad0cc94b1",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title: "TIDE 2.0",
    websiteUrl:
      "https://www.siicincubator.com/programs/programs_tide_mvp_grant.php",
    fundingAmount: null,
    targetIndustry:
      "Education, Agriculture, Transportation, Finance Technology",
    targetSector: "",
    targetWomenFounder: null,
    targetProductStage: ["Ideation", "Minimum viable product (MVP)"],
    targetFundingStage: ["Pre-Seed"],
    description:
      "Startup Incubation and Innovation Centre, IIT Kanpur (incubatoriitk) invites startups and entrepreneurs to apply for the TIDE 2.0 MVP Grant Program, designed to support the development of Minimum Viable Products (MVPs) for innovative solutions.\n\nProgram Benefits:\n\n- Financial Grant: Up to INR 7 Lakh per startup, available for one year.\n- Infrastructure Access: Utilize IIT Kanpur's state-of-the-art facilities and co-working spaces.\n- Expert Support: Gain personalized mentoring and guidance on product development, commercialization strategies, and market readiness.\n\nThis grant is specifically tailored for innovators who want to bring their ideas to life and enhance their growth potential. Transform your vision into reality with TIDE 2.0 at SIIC, IIT Kanpur!",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://connect.siicincubator.com/tide/mvp/applications",
    userId: null,
  },
  {
    id: "87a8b51b-d449-44bd-aae1-5aa307eff4f8",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title: "AIIDE Centre of Excellence – Cohort 4",
    websiteUrl: "https://www.aiidecoe.com/",
    fundingAmount: null,
    targetIndustry: "AI (Artificial Intelligence)",
    targetSector: "Machine Learning",
    targetWomenFounder: null,
    targetProductStage: [
      "Ideation",
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
      "Go-to-market",
      "Growth and scale",
    ],
    targetFundingStage: ["Pre-Seed", "Seed"],
    description:
      'Call for Applications: AIIDE Centre of Excellence – Cohort 4\n\nThe Government of Uttar Pradesh invites applications for Cohort-4 of the Artificial Intelligence and Innovation-Driven Entrepreneurship (AIIDE) Centre of Excellence (CoE) under the Start in UP scheme. Managed by Startup Incubation and Innovation Centre, IIT Kanpur (incubatoriitk), Indian Institute of Technology, Kanpur in collaboration with FICCI, the CoE supports startups in AI, ICT, IoT, Cybersecurity, and related fields. \n\nWhy Apply?\nJoin a thriving community of over 100 startups supported across three cohorts. Access world-class mentorship, resources, and opportunities to advance your ideas in AI/ML and other tech domains. \n\nEligibility:\n- Registered with DPIIT and "Start in UP." \n- Working in or integrating AI/ML into ventures in fields like:  MedTech, AgriTech, EdTech, Fintech, Cleantech, IoT, and more.',
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink: "https://aiidecoe.accubate.app/ext/form/2887/1/apply",
    userId: null,
  },
  {
    id: "e5f052b5-2209-4e89-adc1-896db34cd93a",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title: "Amrita TBI Meity Startup Hub Genesis EIR",
    websiteUrl: "https://www.amritatbi.com/meity-startup-hub-genesis-eir.html",
    fundingAmount: null,
    targetIndustry: "",
    targetSector: "",
    targetWomenFounder: null,
    targetProductStage: [
      "Ideation",
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
    ],
    targetFundingStage: ["Pre-Seed"],
    description:
      "Amrita Technology Business Incubator is one of the select implementing agencies by the MeitY Startup Hub, Government of India. The GENESIS EIR Programme would provide subsistence grant upto to Rs. 10,00,000 per year to an aspiring or budding entrepreneur of considerable potential for pursuing a promising technology business idea.\n\nAmrita TBI is a non-profit startup incubator supported by Govt. of India and Amrita Vishwa Vidyapeetham that funds, mentors and nurtures ideas, startups and entrepreneurs.\n\n1) Startups will receive a grant of upto Rs. 10,00,000/-.\n\n2) You will be given mentorship and handholding for activities related to mentoring sessions, market/customer connect, IPR support, fundraising support, and support needed by the start-up for scaling.\n\nThe MeitY Startup Hub GENESIS EIR support recipient (EIR) will be eligible for a grant of a maximum of Rs.10,00,000/- in a year. Amrita TBI will evaluate the applications according to the guidelines set by MeitY and MSH.\n\nMeitY Startup Hub GENESIS EIR will be monitored very closely for the targeted milestones and is required to submit the progress report furnishing the same as and when needed. Non-Performing MeitY Startup Hub GENESIS EIRs will be terminated even before the completion of 12 months. This funding is subject to your commitment and performance.",
    eligibility:
      "Entrepreneur Eligibility\n1. Nationality:\n- The applicant must be an Indian citizen.\n2. Age:\n- The entrepreneur must be at least 18 years old at the time of application.\n3. Commitment:\n- The applicant must be a first-generation entrepreneur and committed to working full-time on the proposed startup idea during the EiR program duration.\n\nStartup/Idea Eligibility\n1. Stage of the Startup:\n- The startup should be in the ideation, validation, or very early stages.\n- Must not have received significant external funding (exceeding ₹10 lakh, including government grants).\n2. Sector Focus:\n- The proposed startup should focus on technology innovation aligned with the GENESIS scheme’s objectives\n  ❖ Electronics & IT\n  ❖ Emerging technologies (AI, IoT, Blockchain, etc.)\n  ❖ Digital solutions addressing societal challenges (e.g., health, education, agriculture, sustainability).\n3. Scalability and Impact:\n- The startup must have the potential for scalability and create a measurable impact, especially in Tier 2 and Tier 3 cities.\n4. Legal Compliance:\n- If the startup is already incorporated, it must be registered as a Private Limited Company, and LLP under applicable Indian laws.\n- The entity must not be older than 1 year at the time of application.\n5. Originality:\n- The startup idea must be original and not involve duplication of existing products/services or any form of plagiarism.\n\nFunding and Financial Eligibility\n1. No Prior Funding Obligations:\n- The applicant or startup should not have already received significant private or government funding for the same idea.\n- Startups that have availed of government support under other schemes for the same concept may not be eligible.\n2. Grant Utilization:\n- The entrepreneur must demonstrate a clear and actionable plan for utilizing the EIR support (e.g., prototype development, market research, or customer validation).\n\nAlignment with GENESIS Objectives\n1. The proposed startup/idea should align with the overarching goals of the GENESIS Scheme:\n ❖ Promoting technology-led entrepreneurship.\n ❖ Creating jobs and fostering regional innovation hubs.\n ❖ Supporting sustainable and inclusive economic growth.\n2. The applicant must agree to actively participate in all mentorship programs, workshops, and other activities organized under the EIR program.\n\nExclusions\n1. Individuals currently enrolled in other full-time incubation/entrepreneurship schemes or programs, unless permitted by both programs.\n2. Startups involved in unethical, illegal, or non-compliant business activities.",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://www.amritatbi.com/meity-startup-hub-genesis-eir.html#apply",
    userId: null,
  },
  {
    id: "a83a8ef8-17f5-4587-920c-cf5d63ab7f01",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title: "NEURON- GENESIS EiR Program",
    websiteUrl: "https://sayuj.net/apply-contest/NEURON-GENESIS-EiR",
    fundingAmount: null,
    targetIndustry:
      "Consumer Goods, AI (Artificial Intelligence), Agriculture, Healthcare & Lifesciences, Education",
    targetSector: "Machine Learning, Agri-Tech, HealthTech, EdTech",
    targetWomenFounder: null,
    targetProductStage: ["Ideation", "Minimum viable product (MVP)"],
    targetFundingStage: ["Pre-Seed"],
    description:
      "Call for Entrepreneur-in- Residence (EiR) under Gen-Next Support for Innovative Startups (GENESIS) by Meity Startup Hub (MSH), Government of India.\nName of the Scheme: Gen-Next Support for Innovative Startups (GENESIS)\nFunding Agency: MeitY Startup Hub (MSH), Government of India\nImplementing Agency: STPI-Neuron CoE, Mohali, Punjab (AIC STPINEXT Initiatives)\nFunding Support: Upto 10 Lacs\nLast date to apply: Feb 15, 2025\nOther Support:\nCo-working space\nAccess to labs\nLegal compliance\nIP support and guidance\nPeriodic mentoring\nConnect to domain experts\nNetwork access\nEligibility Criteria:\n1. The EIR applicant should be citizen of India\n2. Early-stage startups\n3. The entity must not be older than 1 year at the time of application\n4.  The applicant must not have received significant external funding (exceeding ₹10 lakh, including government funding)\n5. The startup idea must be original and not involve duplication of existing products/services or any form of plagiarism\nNote: \n\nPriority will be given to startups and entrepreneurs from Tier 2 and Tier 3 cities to promote regional innovation\nTo apply, kindly complete the following form.",
    eligibility:
      "- Registered as a Private Limited Company or LLP\n- Startups must be incorporated within the last 12 months\n- Applicant must not have received significant external funding (exceeding ₹10 lakh, including government grants and funding)\n- Preference for entrepreneurs from Tier II & Tier III cities \n- Startups in ideation, validation, or early stages only",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdosk3H1kKjUODOTRp0n9KbPD7zr5K9lAryD4nIi8-QLwt9wg/viewform",
    userId: null,
  },
  {
    id: "94d5de67-3774-44bf-877c-8f8b1548cdb5",
    imageUrl: null,
    type: "Funding",
    subtype: "Grant",
    title: "KIIT- Genesis EIR",
    websiteUrl: "https://kiitincubator.in/",
    fundingAmount: null,
    targetIndustry:
      "Consumer Goods, AI (Artificial Intelligence), Agriculture, Healthcare & Lifesciences, Education",
    targetSector: "Machine Learning, Agri-Tech, HealthTech, EdTech",
    targetWomenFounder: null,
    targetProductStage: ["Ideation", "Minimum viable product (MVP)"],
    targetFundingStage: ["Pre-Seed"],
    description:
      "nder the hashtag#Genesis Initiative by the Ministry of Electronics and Information Technology, startups can secure a grant of ₹10 Lakhs to fuel their entrepreneurial journey.\n\nFocus Areas:\n 1️⃣ Electronics & IT\n 2️⃣ Emerging Technologies (AI, IoT, Blockchain, etc.)\n 3️⃣ Digital Solutions addressing societal challenges (Health, Education, Agriculture, Sustainability)\n\nThis is your chance to gain financial, technical, and professional support to transform your ideas into impactful innovations.",
    eligibility:
      "- Registered as a Private Limited Company or LLP\n- Startups must be incorporated within the last 12 months\n- Applicant must not have received significant external funding (exceeding ₹10 lakh, including government grants and funding)\n- Preference for entrepreneurs from Tier II & Tier III cities \n- Startups in ideation, validation, or early stages only",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSetcvSsflEu4yR3oGfbVzEVxZseBkantejxIZAsguMEB4gI7Q/viewform",
    userId: null,
  },
  {
    id: "c8ab1fae-f63d-4d7c-88a6-4912d8da5c04",
    imageUrl: null,
    type: "Funding",
    subtype: "Equity",
    title: "D2C Insider Elevate",
    websiteUrl: "https://elevate.d2cinsider.com/",
    fundingAmount: null,
    targetIndustry: "Consumer Goods ",
    targetSector:
      "Fast Moving Consumer Goods (FMCG), Consumer Electronics, Household Products ",
    targetWomenFounder: null,
    targetProductStage: [
      "Minimum viable product (MVP)",
      "Product-market fit (PMF)",
      "Go-to-market",
      "Growth and scale",
    ],
    targetFundingStage: ["Pre-Seed", "Seed", "Series A"],
    description:
      "Are you ready to scale your D2C startup and raise your first cheque?\n\nJoin Elevate Cohort 4, a 12-week growth accelerator designed to transform your 0-1 journey:\n- Raise your 1st Cheque up to 1 Cr. at Pre Seed/Seed stage via D2C Insider Super Angels Fund.\n- Strategic mentorship and personalized guidance for growth.\n- Exclusive Demo Day to pitch your startup to top investors for your next round.\n- Meaningful connections with industry leaders and like-minded founders.",
    eligibility: "",
    bannerUrl: null,
    startDatetime: null,
    endDatetime: null,
    noOfRegistrations: null,
    questions: null,
    registration: null,
    businessId: null,
    registrationFormLink: "https://d2ci.pro.typeform.com/to/cYZOh0CJ",
    userId: null,
  },
];

import axios from "axios";

const baseUrl =
  "https://viseyreccomendation-23e913815003.herokuapp.com/opportunity/data_insert";

const seedRecommendations = async () => {
  opportunities?.forEach((opportunity) => {
    const seed = async () => {
      const res = await axios.post(baseUrl, {
        id: opportunity.id,
        type: opportunity.type || "",
        subtype: opportunity.subtype || "",
        title: opportunity.title || "",
        fundingAmount: opportunity.fundingAmount || 0,
        targetIndustry: opportunity.targetIndustry || "",
        targetSector: opportunity.targetSector || "",
        description: opportunity.description || "",
      });
    };
    seed();
  });
};

seedRecommendations();
